name: mfix-win64
channels:
  - defaults
  - mfix
dependencies:
  - boost=1.65.1
  - cmake-binary=3.9.1
  - flask
  - libboost=1.65.1
  - libboost-mingw
  - libpython=2.1
  - m2w64-toolchain=5.3.0
  - matplotlib
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - numpy=1.14.2
  - pip
  - psutil
  - py-boost=1.65.1
  - pyqt=5.*
  - pyqtgraph
  - python=3.6.*
  - qtpy
  - setuptools
  - simplejson
  - vtk
