package:
  name: libboost-mingw
  version: "1.65.1"

source:
  fn: boost_1_65_1.tar.bz2
  url: https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2
  sha1: 4a5b0c3c1b1b9a4d6cb6a6cc395e903e76f76720

build:
  number: 1

requirements:
  build:
   - m2-base
   - m2w64-toolchain

about:
  home: http://www.boost.org
  license: Boost Software Licence
