#!/usr/bin/env python

# Information about keyword argument types (phase, species, etc) extracted
# from mfix_user_guide

# TODO, move this to project_manager and get directly from keyword_doc
# instead of this inline dict
# Note, running this file will regenerate the keyword_args dictionary.
#  Do not edit by hand

keyword_args = {
    'added_mass': (),
    'adjust_proc_domain_size': (),
    'aggregation_eff': (),
    'alpha_max': (),
    'asperities': (),
    'auto_restart': (),
    'automatic_restart': (),
    'bar_char': (),
    'bar_resolution': (),
    'bar_width': (),
    'batch_wallclock': (),
    'bc_c_scalar': ('bc', 'scalar'),
    'bc_c_t_g': ('bc',),
    'bc_c_t_s': ('bc', 'phase'),
    'bc_c_theta_m': ('bc', 'phase'),
    'bc_c_x_g': ('bc', 'species'),
    'bc_c_x_s': ('bc', 'phase', 'species'),
    'bc_dt_0': ('bc',),
    'bc_dt_h': ('bc',),
    'bc_dt_l': ('bc',),
    'bc_e_turb_g': ('bc',),
    'bc_ep_g': ('bc',),
    'bc_ep_s': ('bc', 'phase'),
    'bc_hw_g': ('bc',),
    'bc_hw_s': ('bc', 'phase'),
    'bc_hw_scalar': ('bc', 'scalar'),
    'bc_hw_t_g': ('bc',),
    'bc_hw_t_s': ('bc', 'phase'),
    'bc_hw_theta_m': ('bc', 'phase'),
    'bc_hw_x_g': ('bc', 'species'),
    'bc_hw_x_s': ('bc', 'phase', 'species'),
    'bc_i_e': ('bc',),
    'bc_i_w': ('bc',),
    'bc_id_q': ('quadric',),
    'bc_j_n': ('bc',),
    'bc_j_s': ('bc',),
    'bc_jet_g0': ('bc',),
    'bc_jet_gh': ('bc',),
    'bc_jet_gl': ('bc',),
    'bc_jj_m': (),
    'bc_jj_ps': ('bc',),
    'bc_k_b': ('bc',),
    'bc_k_t': ('bc',),
    'bc_k_turb_g': ('bc',),
    'bc_massflow_g': ('bc',),
    'bc_massflow_s': ('bc', 'phase'),
    'bc_p_g': ('bc',),
    'bc_pic_mi_const_npc': ('bc', 'phase'),
    'bc_pic_mi_const_statwt': ('bc', 'phase'),
    'bc_po_apply_to_des': ('bc',),
    'bc_rop_s': ('bc', 'phase'),
    'bc_scalar': ('bc', 'scalar'),
    'bc_scalarw': ('bc', 'scalar'),
    'bc_t_g': ('bc',),
    'bc_t_s': ('bc', 'phase'),
    'bc_theta_m': ('bc', 'phase'),
    'bc_thetaw_m': ('bc', 'phase'),
    'bc_tw_g': ('bc',),
    'bc_tw_s': ('bc', 'phase'),
    'bc_type': ('bc',),
    'bc_u_g': ('bc',),
    'bc_u_s': ('bc', 'phase'),
    'bc_uw_g': ('bc',),
    'bc_uw_s': ('bc', 'phase'),
    'bc_v_g': ('bc',),
    'bc_v_s': ('bc', 'phase'),
    'bc_volflow_g': ('bc',),
    'bc_volflow_s': ('bc', 'phase'),
    'bc_vw_g': ('bc',),
    'bc_vw_s': ('bc', 'phase'),
    'bc_w_g': ('bc',),
    'bc_w_s': ('bc', 'phase'),
    'bc_ww_g': ('bc',),
    'bc_ww_s': ('bc', 'phase'),
    'bc_x_e': ('bc',),
    'bc_x_g': ('bc', 'species'),
    'bc_x_s': ('bc', 'phase', 'species'),
    'bc_x_w': ('bc',),
    'bc_xw_g': ('bc', 'species'),
    'bc_xw_s': ('bc', 'phase', 'species'),
    'bc_y_n': ('bc',),
    'bc_y_s': ('bc',),
    'bc_z_b': ('bc',),
    'bc_z_t': ('bc',),
    'bdist_io': (),
    'bend_r1': ('quadric',),
    'bend_r2': ('quadric',),
    'bend_theta1': ('quadric',),
    'bend_theta2': ('quadric',),
    'blending_function': (),
    'breakage_eff': (),
    'breakdown_solid_inventory_by_phase': (),
    'bstart_with_one_res': (),
    'bwrite_netcdf': ('netcdf',),
    'c': ('user-defined',),
    'c2c_r1': ('quadric',),
    'c2c_r2': ('quadric',),
    'c2c_y1': ('quadric',),
    'c2c_y2': ('quadric',),
    'c_e': (),
    'c_f': (),
    'c_name': ('user-defined',),
    'c_pg0': (),
    'c_ps0': ('phase',),
    'cad_propagate_order': (),
    'call_dqmom': (),
    'call_usr': (),
    'call_usr_source': ('equation',),
    'cartesian_grid': (),
    'cfl_pic': (),
    'cg_safe_mode': (),
    'cg_ur_fac': (),
    'chi_scheme': (),
    'chk_batchq_end': (),
    'clip_xmax': ('quadric',),
    'clip_xmin': ('quadric',),
    'clip_ymax': ('quadric',),
    'clip_ymin': ('quadric',),
    'clip_zmax': ('quadric',),
    'clip_zmin': ('quadric',),
    'close_packed': ('phase',),
    'cn_on': (),
    'coordinates': (),
    'cpx': ('ctrl',),
    'cpy': ('ctrl',),
    'cpz': ('ctrl',),
    'cyclic_x': (),
    'cyclic_x_pd': (),
    'cyclic_y': (),
    'cyclic_y_pd': (),
    'cyclic_z': (),
    'cyclic_z_pd': (),
    'cylindrical_2d': (),
    'd_p0': ('phase',),
    'dbgprn_layout': (),
    'debug_des': (),
    'debug_resid': (),
    'def_cor': (),
    'delp_x': (),
    'delp_y': (),
    'delp_z': (),
    'des_coll_model': (),
    'des_conv_corr': (),
    'des_diffuse_width': (),
    'des_em': ('phase',),
    'des_en_input': ('index',),
    'des_en_wall_input': ('index',),
    'des_et_input': ('index',),
    'des_et_wall_input': ('index',),
    'des_etat_fac': (),
    'des_etat_w_fac': (),
    'des_explicitly_coupled': (),
    'des_interp_mean_fields': (),
    'des_interp_on': (),
    'des_interp_scheme': (),
    'des_interp_width': (),
    'des_intg_method': (),
    'des_min_cond_dist': (),
    'des_neighbor_search': (),
    'des_oneway_coupled': (),
    'des_output_type': (),
    'des_report_mass_interp': (),
    'des_usr_var_size': (),
    'description': (),
    'desgridsearch_imax': (),
    'desgridsearch_jmax': (),
    'desgridsearch_kmax': (),
    'detect_stall': (),
    'dif_g0': (),
    'dif_s0': ('phase',),
    'dil_factor_vsd': (),
    'dil_inert_x_vsd': ('phase',),
    'dim_facets_per_cell': (),
    'discretize': ('equation',),
    'do_transpose': (),
    'dquadric': ('quadric',),
    'drag_c1': (),
    'drag_d1': (),
    'drag_type': (),
    'dt': (),
    'dt_fac': (),
    'dt_max': (),
    'dt_min': (),
    'dwall_brute_force': (),
    'dx': ('cell',),
    'dy': ('cell',),
    'dz': ('cell',),
    'e_w': (),
    'e_young': ('phase',),
    'e_young_actual': ('phase',),
    'enable_dmp_log': (),
    'energy_eq': (),
    'ep_s_max': ('phase',),
    'ep_star': (),
    'eps_f_min': (),
    'erx': ('ctrl',),
    'ery': ('ctrl',),
    'erz': ('ctrl',),
    'ew_young': (),
    'ew_young_actual': (),
    'f_dashboard': (),
    'fac_dim_max_cut_cell': (),
    'factor_rlm': (),
    'fedors_landel': (),
    'filter_size_ratio': (),
    'first_dx': ('ctrl',),
    'first_dy': ('ctrl',),
    'first_dz': ('ctrl',),
    'flip_stl_normals': ('bc',),
    'flpc': (),
    'fluid_in_clipped_region': ('quadric',),
    'flux_g': (),
    'focus_particle': (),
    'frame': ('vtk',),
    'fric_exp_pic': (),
    'fric_non_sing_fac': (),
    'friction_model': (),
    'full_log': (),
    'gener_part_config': (),
    'gravity': (),
    'gravity_x': (),
    'gravity_y': (),
    'gravity_z': (),
    'group_q': ('group', 'quadric'),
    'group_relation': ('group',),
    'group_resid': (),
    'group_size': ('group',),
    'half_angle': ('quadric',),
    'hamaker_constant': (),
    'i_cyl_num': (),
    'i_cyl_transition': (),
    'ic_des_fit_to_region': ('ic',),
    'ic_e_turb_g': ('ic',),
    'ic_ep_g': ('ic',),
    'ic_ep_s': ('ic', 'phase'),
    'ic_gama_rg': ('ic',),
    'ic_gama_rs': ('ic', 'phase'),
    'ic_i_e': ('ic',),
    'ic_i_w': ('ic',),
    'ic_j_n': ('ic',),
    'ic_j_s': ('ic',),
    'ic_k_b': ('ic',),
    'ic_k_t': ('ic',),
    'ic_k_turb_g': ('ic',),
    'ic_l_scale': ('ic',),
    'ic_p_g': ('ic',),
    'ic_p_star': ('ic',),
    'ic_pic_const_npc': ('ic', 'phase'),
    'ic_pic_const_statwt': ('ic', 'phase'),
    'ic_rop_s': ('ic', 'phase'),
    'ic_scalar': ('ic', 'scalar'),
    'ic_t_g': ('ic',),
    'ic_t_rg': ('ic',),
    'ic_t_rs': ('ic', 'phase'),
    'ic_t_s': ('ic', 'phase'),
    'ic_theta_m': ('ic', 'phase'),
    'ic_type': ('ic',),
    'ic_u_g': ('ic',),
    'ic_u_s': ('ic', 'phase'),
    'ic_v_g': ('ic',),
    'ic_v_s': ('ic', 'phase'),
    'ic_w_g': ('ic',),
    'ic_w_s': ('ic', 'phase'),
    'ic_x_e': ('ic',),
    'ic_x_g': ('ic', 'species'),
    'ic_x_s': ('ic', 'phase', 'species'),
    'ic_x_w': ('ic',),
    'ic_y_n': ('ic',),
    'ic_y_s': ('ic',),
    'ic_z_b': ('ic',),
    'ic_z_t': ('ic',),
    'icheck_bicgs': (),
    'imax': (),
    'inert_species': ('phase',),
    'is_i_e': ('is',),
    'is_i_w': ('is',),
    'is_j_n': ('is',),
    'is_j_s': ('is',),
    'is_k_b': ('is',),
    'is_k_t': ('is',),
    'is_pc': ('is', 'idx'),
    'is_serial': (),
    'is_type': ('is',),
    'is_vel_s': ('is', 'phase'),
    'is_x_e': ('is',),
    'is_x_w': ('is',),
    'is_y_n': ('is',),
    'is_y_s': ('is',),
    'is_z_b': ('is',),
    'is_z_t': ('is',),
    'ishii': (),
    'iter_restart': (),
    'itermax_int': (),
    'jackson': (),
    'jenkins': (),
    'jmax': (),
    'k_g0': (),
    'k_s0': ('phase',),
    'kmax': (),
    'kn': (),
    'kn_w': (),
    'kt_fac': (),
    'kt_type': (),
    'kt_w_fac': (),
    'lam_hys': (),
    'lambda_x': ('quadric',),
    'lambda_y': ('quadric',),
    'lambda_z': ('quadric',),
    'last_dx': ('ctrl',),
    'last_dy': ('ctrl',),
    'last_dz': ('ctrl',),
    'leq_it': ('equation',),
    'leq_method': ('equation',),
    'leq_pc': ('equation',),
    'leq_sweep': ('equation',),
    'leq_tol': ('equation',),
    'm_am': (),
    'max_inlet_vel_fac': (),
    'max_nit': (),
    'mew': (),
    'mew_w': (),
    'minimize_des_facet_list': (),
    'minimize_send_recv': (),
    'mmax': (),
    'model_b': (),
    'momentum_x_eq': ('phase',),
    'momentum_y_eq': ('phase',),
    'momentum_z_eq': ('phase',),
    'monitor_dt': ('monitor',),
    'monitor_e_turb_g': ('monitor',),
    'monitor_ep_g': ('monitor',),
    'monitor_k_turb_g': ('monitor',),
    'monitor_name': ('monitor',),
    'monitor_p_g': ('monitor',),
    'monitor_p_star': ('monitor',),
    'monitor_ro_g': ('monitor',),
    'monitor_ro_s': ('monitor', 'phase'),
    'monitor_rop_s': ('monitor', 'phase'),
    'monitor_rrate': ('monitor', 'rrate'),
    'monitor_scalar': ('monitor', 'scalar'),
    'monitor_t_g': ('monitor',),
    'monitor_t_s': ('monitor', 'phase'),
    'monitor_theta_m': ('monitor', 'phase'),
    'monitor_type': ('monitor',),
    'monitor_u_g': ('monitor',),
    'monitor_u_s': ('monitor', 'phase'),
    'monitor_v_g': ('monitor',),
    'monitor_v_s': ('monitor', 'phase'),
    'monitor_w_g': ('monitor',),
    'monitor_w_s': ('monitor', 'phase'),
    'monitor_x_e': ('monitor',),
    'monitor_x_g': ('monitor', 'species'),
    'monitor_x_s': ('monitor', 'phase', 'species'),
    'monitor_x_w': ('monitor',),
    'monitor_y_n': ('monitor',),
    'monitor_y_s': ('monitor',),
    'monitor_z_b': ('monitor',),
    'monitor_z_t': ('monitor',),
    'mppic_coeff_en1': (),
    'mppic_coeff_en2': (),
    'mppic_coeff_en_wall': (),
    'mppic_coeff_et_wall': (),
    'mppic_grav_treatment': (),
    'mppic_pdrag_implicit': (),
    'mppic_solid_stress_snider': (),
    'mu_g0': (),
    'mu_gmax': (),
    'mu_s0': ('phase',),
    'mw_avg': (),
    'mw_g': ('species',),
    'mw_s': ('phase', 'species'),
    'n_group': (),
    'n_quadric': (),
    'n_usr_def': (),
    'n_x': ('quadric',),
    'n_y': ('quadric',),
    'n_z': ('quadric',),
    'ncx': ('ctrl',),
    'ncy': ('ctrl',),
    'ncz': ('ctrl',),
    'neighbor_search_n': (),
    'neighbor_search_rad_ratio': (),
    'nfactor': (),
    'nlog': (),
    'nmax': ('phase',),
    'nmax_g': (),
    'nmax_s': ('phase',),
    'no_k': (),
    'nodesi': (),
    'nodesi_report': (),
    'nodesj': (),
    'nodesj_report': (),
    'nodesk': (),
    'nodesk_report': (),
    'norm_g': (),
    'norm_s': (),
    'nrr': (),
    'nscalar': (),
    'opt_parallel': (),
    'out_dt': (),
    'out_msh_value': (),
    'out_stl_value': (),
    'p_ref': (),
    'p_scale': (),
    'particles': (),
    'persistent_mode': (),
    'pg_option': (),
    'phase4scalar': ('scalar',),
    'phi': (),
    'phi_w': (),
    'phip': (),
    'phip0': (),
    'phip_out_jj': (),
    'pic_report_deletion_stats': (),
    'pic_report_min_epg': (),
    'pic_report_seeding_stats': (),
    'piece_xmax': ('quadric',),
    'piece_xmin': ('quadric',),
    'piece_ymax': ('quadric',),
    'piece_ymin': ('quadric',),
    'piece_zmax': ('quadric',),
    'piece_zmin': ('quadric',),
    'ppo': (),
    'print_des_data': (),
    'print_progress_bar': (),
    'print_warnings': (),
    'ps_i_e': ('ps',),
    'ps_i_w': ('ps',),
    'ps_j_n': ('ps',),
    'ps_j_s': ('ps',),
    'ps_k_b': ('ps',),
    'ps_k_t': ('ps',),
    'ps_massflow_g': ('ps',),
    'ps_massflow_s': ('ps', 'phase'),
    'ps_t_g': ('ps',),
    'ps_t_s': ('ps', 'phase'),
    'ps_u_g': ('ps',),
    'ps_u_s': ('ps', 'phase'),
    'ps_v_g': ('ps',),
    'ps_v_s': ('ps', 'phase'),
    'ps_w_g': ('ps',),
    'ps_w_s': ('ps', 'phase'),
    'ps_x_e': ('ps',),
    'ps_x_g': ('ps', 'species'),
    'ps_x_s': ('ps', 'phase', 'species'),
    'ps_x_w': ('ps',),
    'ps_y_n': ('ps',),
    'ps_y_s': ('ps',),
    'ps_z_b': ('ps',),
    'ps_z_t': ('ps',),
    'psfac_fric_pic': (),
    'quadric_form': ('quadric',),
    'quadric_scale': (),
    'r_p': ('phase', 'phase'),
    'radius': ('quadric',),
    'ray_dir': (),
    'rdf_type': (),
    're_indexing': (),
    'reactor1_r1': ('quadric',),
    'reactor1_r2': ('quadric',),
    'reactor1_rr1': ('quadric',),
    'reactor1_rr2': ('quadric',),
    'reactor1_theta1': ('quadric',),
    'reactor1_theta2': ('quadric',),
    'reactor1_y1': ('quadric',),
    'reactor1_y2': ('quadric',),
    'reactor1_yr1': ('quadric',),
    'reactor1_yr2': ('quadric',),
    'relation_with_previous': ('group',),
    'report_best_domain_size': (),
    'report_mass_balance_dt': (),
    'report_neg_density': (),
    'report_neg_specificheat': (),
    'report_solid_inventory': (),
    'report_solid_inventory_dt': (),
    'res_backup_dt': (),
    'res_backups': (),
    'res_dt': (),
    'resid_string': ('residual',),
    'ro_g0': (),
    'ro_s0': ('phase',),
    'ro_xs0': ('phase', 'species'),
    'run_name': (),
    'run_type': (),
    'scale_msh': (),
    'scale_stl': (),
    'segregation_slope_coefficient': (),
    'set_corner_cells': (),
    'shear': (),
    'solids_model': ('phase',),
    'solver_statistics': (),
    'species_alias_g': ('species',),
    'species_alias_s': ('phase', 'species'),
    'species_eq': ('phase',),
    'species_g': ('species',),
    'species_name': ('phase',),
    'species_s': ('phase', 'species'),
    'spx_dt': ('sp',),
    'stiff_chem_max_steps': (),
    'stiff_chemistry': (),
    'stl_bc_id': (),
    'stl_small_angle': (),
    'subgrid_type': (),
    'subgrid_wall': (),
    't_x': ('quadric',),
    't_y': ('quadric',),
    't_z': ('quadric',),
    'term_buffer': (),
    'theta_x': ('quadric',),
    'theta_y': ('quadric',),
    'theta_z': ('quadric',),
    'time': (),
    'time_dependent_filename': (),
    'tol_delh': (),
    'tol_diverge': (),
    'tol_f': (),
    'tol_merge': (),
    'tol_msh': (),
    'tol_poly': (),
    'tol_resid': (),
    'tol_resid_k_epsilon': (),
    'tol_resid_scalar': (),
    'tol_resid_t': (),
    'tol_resid_th': (),
    'tol_resid_x': (),
    'tol_small_area': (),
    'tol_small_cell': (),
    'tol_snap': ('direction',),
    'tol_stl': (),
    'tol_stl_dp': (),
    'torus_r1': ('quadric',),
    'torus_r2': ('quadric',),
    'tstop': (),
    'turbulence_model': (),
    'tx_msh': (),
    'tx_stl': (),
    'ty_msh': (),
    'ty_stl': (),
    'tz_msh': (),
    'tz_stl': (),
    'ucoil_r1': ('quadric',),
    'ucoil_r2': ('quadric',),
    'ucoil_y1': ('quadric',),
    'ucoil_y2': ('quadric',),
    'units': (),
    'ur_f_gs': (),
    'ur_fac': ('equation',),
    'ur_kth_sml': (),
    'use_cohesion': (),
    'use_doloop': (),
    'use_msh': (),
    'use_polygon': (),
    'use_rrates': (),
    'use_stl': (),
    'use_vdh_dem_model': (),
    'usr_cpg': (),
    'usr_cps': ('phase',),
    'usr_difg': (),
    'usr_difs': ('phase',),
    'usr_dt': ('usr',),
    'usr_ext': ('usr',),
    'usr_fgs': ('phase',),
    'usr_format': ('usr',),
    'usr_fss': ('phase',),
    'usr_gama': ('phase',),
    'usr_i_e': ('usr',),
    'usr_i_w': ('usr',),
    'usr_j_n': ('usr',),
    'usr_j_s': ('usr',),
    'usr_k_b': ('usr',),
    'usr_k_t': ('usr',),
    'usr_kg': (),
    'usr_ks': ('phase',),
    'usr_mug': (),
    'usr_mus': ('phase',),
    'usr_rog': (),
    'usr_ros': ('phase',),
    'usr_type': ('usr',),
    'usr_var': ('usr',),
    'usr_x_e': ('usr',),
    'usr_x_w': ('usr',),
    'usr_y_n': ('usr',),
    'usr_y_s': ('usr',),
    'usr_z_b': ('usr',),
    'usr_z_t': ('usr',),
    'v_ex': (),
    'v_poisson': ('phase',),
    'v_poisson_actual': ('phase',),
    'v_sh': (),
    'van_der_waals': (),
    'vdw_inner_cutoff': (),
    'vdw_outer_cutoff': (),
    'vtk_bc_id': ('vtk',),
    'vtk_cutcell_only': ('vtk',),
    'vtk_data': ('vtk',),
    'vtk_dbg_file': ('vtk',),
    'vtk_debug': ('vtk', 'idx'),
    'vtk_dt': ('vtk',),
    'vtk_dwall': ('vtk',),
    'vtk_e_turb_g': ('vtk',),
    'vtk_ep_g': ('vtk',),
    'vtk_facet_count_des': ('vtk',),
    'vtk_filebase': ('vtk',),
    'vtk_ijk': ('vtk',),
    'vtk_k_turb_g': ('vtk',),
    'vtk_lambda_2': ('vtk',),
    'vtk_nb_facet_des': ('vtk',),
    'vtk_normal': ('vtk',),
    'vtk_nxs': ('vtk',),
    'vtk_nys': ('vtk',),
    'vtk_nzs': ('vtk',),
    'vtk_p_g': ('vtk',),
    'vtk_p_star': ('vtk',),
    'vtk_part_angular_vel': ('vtk',),
    'vtk_part_cohesion': ('vtk',),
    'vtk_part_density': ('vtk',),
    'vtk_part_diameter': ('vtk',),
    'vtk_part_id': ('vtk',),
    'vtk_part_orientation': ('vtk',),
    'vtk_part_phase': ('vtk', 'phase'),
    'vtk_part_rank': ('vtk',),
    'vtk_part_temp': ('vtk',),
    'vtk_part_usr_var': ('vtk', 'usr_var'),
    'vtk_part_vel': ('vtk',),
    'vtk_part_x_s': ('vtk', 'species'),
    'vtk_partition': ('vtk',),
    'vtk_rop_s': ('vtk', 'phase'),
    'vtk_rrate': ('vtk', 'rate'),
    'vtk_rrate_label': ('vtk', 'rate'),
    'vtk_scalar': ('vtk', 'scalar'),
    'vtk_select_mode': ('vtk',),
    'vtk_slice_tol': ('vtk',),
    'vtk_t_g': ('vtk',),
    'vtk_t_s': ('vtk', 'phase'),
    'vtk_theta_m': ('vtk', 'phase'),
    'vtk_u_g': ('vtk',),
    'vtk_u_s': ('vtk', 'phase'),
    'vtk_v_g': ('vtk',),
    'vtk_v_s': ('vtk', 'phase'),
    'vtk_var': ('idx',),
    'vtk_vel_g': ('vtk',),
    'vtk_vel_s': ('vtk', 'phase'),
    'vtk_vorticity': ('vtk',),
    'vtk_w_g': ('vtk',),
    'vtk_w_s': ('vtk', 'phase'),
    'vtk_x_e': ('vtk',),
    'vtk_x_g': ('vtk', 'species'),
    'vtk_x_s': ('vtk', 'phase', 'species'),
    'vtk_x_w': ('vtk',),
    'vtk_y_n': ('vtk',),
    'vtk_y_s': ('vtk',),
    'vtk_z_b': ('vtk',),
    'vtk_z_t': ('vtk',),
    'vtp_dir': (),
    'vtu_dir': (),
    'vw_poisson': (),
    'vw_poisson_actual': (),
    'wall_hamaker_constant': (),
    'wall_vdw_inner_cutoff': (),
    'wall_vdw_outer_cutoff': (),
    'write_dashboard': (),
    'write_vtk_files': (),
    'x_max': (),
    'x_min': (),
    'x_s0': ('phase', 'species'),
    'xlength': (),
    'xmin': (),
    'y_max': (),
    'y_min': (),
    'ylength': (),
    'yu_standish': (),
    'z_max': (),
    'z_min': (),
    'zlength': ()}


arg_types = set()
for (k, v) in keyword_args.items():
    arg_types.update(v)

keys_by_type = {}
for t in arg_types:
    keys_by_type[t] = [k for (k, v) in keyword_args.items() if t in v]
    keys_by_type[t].sort()


def mkargs(key, **value_dict):
    args = keyword_args.get(key)
    if args is None:
        return
    if 'is_' in value_dict:
        value_dict['is'] = value_dict['is_']
    r = [value_dict.get(a, a) for a in args]
    return r

if (__name__ == '__main__'):
    import mfixgui.namelistparser as NP
    from pprint import pformat
    d = NP.getKeywordDoc()

    def normalize(arg):
        arg = arg.lower()
        if 'species' in arg:
            return 'species'
        return arg.split()[0].replace('+1','')

    keyword_args = dict((k, tuple(normalize(a['id'])
                                  for a in d[k]['args'].values()))
                        for k in d.keys())
    s = pformat(keyword_args, indent=4)
    skip = False
    for line in open(__file__, encoding='utf-8', errors='replace'):
        if line.startswith('keyword_args ='):
            print('keyword_args = {\n ', end='')
            print(s[1:])
            skip = True
        if not skip:
            print(line, end='')
        elif '}' in line:
            skip = False
